# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwiftyJsonDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftyJSON', '~>3.1.4'

  # Pods for SwiftyJsonDemo

  target 'SwiftyJsonDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftyJsonDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
